---
- name: Create folder for jenkins_home if it does not exist
  file:
    path: /home/ubuntu/jenkins_home/keystore
    state: directory
    mode: '0777'

- name: generate jenkins keystore for self-signed certificate 
  docker_container:
    name: openjdk
    image: "openjdk:8"
    auto_remove: yes
    detach: yes
    volumes: "/home/ubuntu/jenkins_home/keystore/:/keystore/"
    working_dir: "/keystore/"
    command: "keytool -genkey -keyalg RSA -alias selfsigned -keystore jenkins_keystore.jks -storepass {{ lookup('password', '/home/ubuntu/jenkins_home/keystore/cert_pass chars=ascii_letters,digits,hexdigits,punctuation') }} -keysize 2048"

- name: run jenkins container
  docker_container:
    name: jenkins
    image: warp0/jenkins:1.0
    auto_remove: yes
    detach: yes
    published_ports: 443:8443
    volumes: /home/ubuntu/jenkins_home:/var/jenkins_home
    env:
      httpPort: "-1"
      httpsPort: "8443"
      httpsKeyStore: "/var/jenkins_home/keystore/jenkins_keystore.jks"
      httpsKeyStorePassword: "{{ lookup('password', '/home/ubuntu/jenkins_home/keystore/cert_pass') }}"
