---
- name: Create folder for jenkins_home if it does not exist
  file:
    path: /home/ubuntu/jenkins_home
    state: directory
    mode: '0777'

- name: run jenkins container
  docker_container:
    name: jenkins
    image: warp0/jenkins:1.0
    auto_remove: yes
    detach: yes
    published_ports: 8080:8080
    volumes: /home/ubuntu/jenkins_home:/var/jenkins_home