---
- name: generate jenkins keystore for self-signed certificate
  run_once: true
  docker_container:
    name: openjdk
    image: openjdk:8
    auto_remove: no
    detach: no
    volumes: /home/ubuntu/jenkins_home:/keystore
    working_dir: /keystore/
    command: keytool -genkey -keyalg RSA -keysize 4096 -alias jenkins -noprompt -dname "CN={{  jenkins_dns  }}, OU=jenkins, O=EPAM, L=Graduate, S=Work, C=UA" -keystore jenkins_keystore.jks -storepass password -keypass password


- name: modify permissions
  file:
    path: /home/ubuntu/jenkins_home
    state: directory
    mode: '0777'
    recurse: yes
    owner: ubuntu
    group: ubuntu 

- name: run jenkins container
  shell: "sudo docker run -d -v /home/ubuntu/jenkins_home:/var/jenkins_home -p 443:8443 warp0/jenkins:1.2 --httpPort=-1 --httpsPort=8443 --httpsKeyStore=/var/jenkins_home/jenkins_keystore.jks --httpsKeyStorePassword=password"
