---
- name: generate jenkins keystore for self-signed certificate
  run_once: true
  docker_container:
    name: openjdk
    image: openjdk:8
    auto_remove: no
    detach: no
    volumes: /home/ubuntu/jenkins_home/keystore/:/keystore/
    working_dir: /keystore/
    command: keytool -genkey -keyalg RSA -keypass -alias selfsigned -keystore jenkins_keystore.jks -storepass password -keysize 2048 -dname "CN={{ jenkins_dns }}, OU=ID, O=IBM, L=Hursley, S=Hants, C=GB"

- name: modify permissions
  file:
    path: /home/ubuntu/jenkins_home
    state: directory
    mode: '0777'
    recurse: yes

- name: run jenkins container
  docker_container:
    name: jenkins
    image: warp0/jenkins:1.0
    auto_remove: yes
    detach: yes
    published_ports: 443:8443
    volumes: /home/ubuntu/jenkins_home:/var/jenkins_home
    env:
      httpPort: "-1"
      httpsPort: "8443"
      httpsKeyStore: "/var/jenkins_home/keystore/jenkins_keystore.jks"
      httpsKeyStorePassword: "password"
