node {
    stage('Preparation') {
        git 'https://github.com/warp0/spring-boot.git'
    }
    stage('Build') {
        sh '(cd ./spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-web-ui/; mvn clean install)'
    }
    stage('Results') {
        archiveArtifacts '**/*.jar'
    }
    stage('upload to artifactory') {
        def server = Artifactory.server'artifactory'
        def build_number = env.BUILD_NUMBER
        def uploadSpec = """{
  "files": [
    {
      "pattern": "/var/jenkins_home/workspace/spring/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-web-ui/target/*.jar",
      "target": "libs-snapshot-local/$build_number/spring-boot-web-ui.jar"
    }
 ]
}"""
        server.upload(uploadSpec)
        
    }
}