node {
    stage('Preparation') {
        git
          url: 'https://github.com/warp0/spring-boot.git'
          branch: dev
    }
    stage('Build') {
        sh '(cd ./spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-web-ui/; mvn clean install)'
    }
    stage('Results') {
        archiveArtifacts '**/*.jar'
    }
    stage('upload to artifactory') {
        def server = Artifactory.server'artifactory'
        
        def uploadSpec = """{
  "files": [
    {
      "pattern": "**/target/*.jar",
      "target": "libs-snapshot-local/$env.BUILD_NUMBER/spring-boot-web-ui.jar"
    }
 ]
}"""
        server.upload(uploadSpec)
        
    }

    stage('deploy')
      
      sshCommand
        remote[:]
          remote.name: 'deployer'
          remote.host: ''
          remote.user: 'ubuntu'
          allowAnyHosts: 'true'
          identity: 
        command: "sudo ansible-playbook -i /home/ubuntu/ansible/hosts -u ubuntu -e 'artifactory_ip=____ build_number=1 deploy=false' /home/ubuntu/ansible/deploy.yml" 

}