---
- name:  download artifact
  get_url: 
    url: "http://{{ artifactory_ip }}:8081/artifactory/libs-snapshot-local/10/.jar" #artifactory_ip is defined in exprort_ip job
    dest: ~/webapp/
    url_username: "admin"
    url_password: "admin123"

- name: Create folder for webapp if it does not exist
  file:
    path: /home/ubuntu/webapp
    state: directory
    mode: '0777'

- name: run app
  docker_container:
    name: artifactory
    image: openjdk:8
    auto_remove: yes
    detach: yes
    published_ports: 80:8080
    volumes: /home/ubuntu/webapp/:/temp/jar/
    entrypoint: java -jar /temp/jar/spring-boot-web-ui.jar  
