- hosts: all
  become: true
  roles:
    - role: './install_docker/'

- hosts: artifactory, jenkins
  become: true
  roles:
    - role: './create_swap/'

- hosts: artifactory
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  become: true
  roles:
    - role: './artifactory_run/'

- hosts: jenkins
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  become: true
  roles:
    - role: './jenkins_run/'