- hosts: all
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  tasks:
  - name: "APT - Add Docker GPG key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: "APT - Add Docker repository"
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present
      filename: docker

#docker dependencies
  - name: "APT - install misc packages"
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - "aptitude"
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "software-properties-common"

  - name: "APT - install 'docker-ce'"
    apt:
      name: "docker-ce"
      update_cache: yes

  #add docker to ubuntu user group & restart
  - name: add user docker to admin group
    user:
      name: docker
      append: yes
      groups: ubuntu

- hosts: artifactory
  become: true
  
  tasks:
  - name: Create swap file
    command: dd if=/dev/zero of=/swapfile bs=1024 count=1500k creates="/swapfile"
    tags:
      - swap.file.create


  - name: Change swap file permissions
    file: path="/swapfile"
          owner=root
          group=root
          mode=0600
    tags:
      - swap.file.permissions


  - name: "Check swap file type"
    command: file /swapfile
    register: swapfile
    tags:
      - swap.file.mkswap


  - name: Make swap file
    command: "sudo mkswap /swapfile"
    tags:
      - swap.file.mkswap


  - name: Write swap entry in fstab
    mount: name=none
          src=/swapfile
          fstype=swap
          opts=sw
          passno=0
          dump=0
          state=present
    tags:
      - swap.fstab


  - name: Mount swap
    command: "swapon /swapfile"
    when: ansible_swaptotal_mb < 1
    tags:
      - swap.file.swapon

  - name: Create folder for jenkins_home if it does not exist
    file:
      path: /home/ubuntu/artifactory_home
      state: directory
      mode: '0755'

  - name: run artifactory
    docker_container:
      name: artifactory
      image: docker.bintray.io/jfrog/artifactory-oss:latest
      auto_remove: yes
      detach: yes
      published_ports: 8081:8081
      volumes: /home/ubuntu/artifactory_home:/var/opt/jfrog/artifactory

- hosts: jenkins
  become: true
 
  tasks:
  - name: Create folder for jenkins_home if it does not exist
    file:
      path: /home/ubuntu/jenkins_home
      state: directory
      mode: '0755'

  - name: run jenkins container
    docker_container:
      name: jenkins
      image: jenkins/jenkins
      auto_remove: yes
      detach: yes
      published_ports: 8080:8080
      volumes: /home/ubuntu/jenkins_home:/var/jenkins_home