- hosts: all
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  tasks:
  - name: "APT - Add Docker GPG key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: "APT - Add Docker repository"
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present
      filename: docker

#docker dependencies
  - name: "APT - install misc packages"
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - "aptitude"
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "software-properties-common"

  - name: "APT - install 'docker-ce'"
    apt:
      name: "docker-ce"
      update_cache: yes

  # sudo apt-get install docker-compose
  - name: Install docker-compose
    apt:
      name: docker-compose
      state: present
      update_cache: yes
    tags:
      - docker
  
  
  #add docker to ubuntu user group & restart
  - name: add user docker to admin group
    user:
      name: docker
      append: yes
      groups: ubuntu

  - name: Restart docker service
    service:
      name: docker
      state: restarted

- hosts: artifactory
  become: true

  tasks:
  - name: run artifactory
    docker_container:
      name: artifactory
      image: docker.bintray.io/jfrog/artifactory-oss:latest
      auto_remove: yes
      detach: yes

- hosts: jenkins
  become: true
 
  tasks:
  - name: run jenkins container
    docker_container:
      name: jenkins
      image: jenkins/jenkins
      auto_remove: yes
      detach: yes
